//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thi
    {
        public string MaSinhVien { get; set; }
        public string MaMonHoc { get; set; }
        public string MaPhong { get; set; }
        public string MaCa { get; set; }
    
        public virtual CaThi CaThi { get; set; }
        public virtual monhoc monhoc { get; set; }
        public virtual phong phong { get; set; }
        public virtual sinhvien sinhvien { get; set; }
    }
}
