//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ESM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bachoc
    {
        public bachoc()
        {
            this.khois = new HashSet<khoi>();
        }
    
        public string MaBacHoc { get; set; }
        public string TenBacHoc { get; set; }
    
        public virtual ICollection<khoi> khois { get; set; }
    }
}
