//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ESM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuyennganh
    {
        public chuyennganh()
        {
            this.sinhviens = new HashSet<sinhvien>();
        }
    
        public string MaChuyenNganh { get; set; }
        public string TenChuyenNganh { get; set; }
        public string KhoaQL { get; set; }
    
        public virtual khoa khoa { get; set; }
        public virtual ICollection<sinhvien> sinhviens { get; set; }
    }
}
