//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ESM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class giaovien
    {

        [ConcurrencyCheck]
        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(5, MinimumLength = 1, ErrorMessage = "Dài từ 1 tới 5 ký tự")]
        [Display(Name = "Mã go viên", Description = "")]
        public string MaGiaoVien { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(15, ErrorMessage = "Không được dài quá 15 ký tự")]
        [Display(Name = "Tên môn học", Description = "")]
        public string TenGiaoVien { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(5, ErrorMessage = "Không được dài quá 5 ký tự")]
        [Display(Name = "Bộ môn", Description = "")]
        public string BoMonQL { get; set; }

        [Display(Name = "Họ lót", Description = "")]
        public string HoLot { get; set; }

        [Display(Name = "Học hàm", Description = "")]
        public string HocHam { get; set; }

        [Display(Name = "Học vị", Description = "")]
        public string HocVi { get; set; }
    
        public virtual bomon bomon { get; set; }
    }
}
