//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ESM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giaovien
    {
        public giaovien()
        {
            this.CaThis = new HashSet<CaThi>();
        }
    
        public string MaGiaoVien { get; set; }
        public string TenGiaoVien { get; set; }
        public string BoMonQL { get; set; }
        public string HoLot { get; set; }
        public string HocHam { get; set; }
        public string HocVi { get; set; }
    
        public virtual bomon bomon { get; set; }
        public virtual ICollection<CaThi> CaThis { get; set; }
    }
}
