//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ESM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monhoc
    {
        public monhoc()
        {
            this.nhoms = new HashSet<nhom>();
        }
    
        public string MaMonHoc { get; set; }
        public string TenMonHoc { get; set; }
        public byte TCLyThuyet { get; set; }
        public byte TCThucHanh { get; set; }
        public byte MonThiNghiem { get; set; }
        public string KhoaXepLich { get; set; }
        public string BoMonQL { get; set; }
        public string GhiChu { get; set; }
    
        public virtual bomon bomon { get; set; }
        public virtual khoa khoa { get; set; }
        public virtual ICollection<nhom> nhoms { get; set; }
    }
}
