//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Mvc_ESM.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel;
    
    public partial class monhoc
    {
        public monhoc()
        {
            this.nhoms = new HashSet<nhom>();
        }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Mã môn học")]
        [StringLength(7,MinimumLength = 1, ErrorMessage = "Dài từ 1 tới 7 ký tự")]
        public string MaMonHoc { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(60, ErrorMessage = "Không được dài quá 60 ký tự")]
        public string TenMonHoc { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [DataType(DataType.Currency, ErrorMessage = "Phải nhập số")] 
        public byte TCLyThuyet { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [DataType(DataType.Currency, ErrorMessage = "Phải nhập số")] 
        public byte TCThucHanh { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [Range(0, 1, ErrorMessage = "Chỉ được nhập 1 hoặc 0")]
        [DataType(DataType.Currency,ErrorMessage = "Phải nhập số")] 
        public byte MonThiNghiem { get; set; }
        
        public string KhoaXepLich { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string BoMonQL { get; set; }
        [StringLength(500,  ErrorMessage = "Không được dài quá 500 ký tự")]
        public string GhiChu { get; set; }
    
        public virtual bomon bomon { get; set; }
        public virtual khoa khoa { get; set; }
        public virtual ICollection<nhom> nhoms { get; set; }
    }
}
