//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ESM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhom
    {
        public nhom()
        {
            this.lichhocvus = new HashSet<lichhocvu>();
            this.pdkmhs = new HashSet<pdkmh>();
            this.lops = new HashSet<lop>();
        }
    
        public string MaMonHoc { get; set; }
        public byte Nhom1 { get; set; }
        public Nullable<int> SiSoDuKien { get; set; }
        public Nullable<int> SoLuongDK { get; set; }
    
        public virtual ICollection<lichhocvu> lichhocvus { get; set; }
        public virtual monhoc monhoc { get; set; }
        public virtual ICollection<pdkmh> pdkmhs { get; set; }
        public virtual ICollection<lop> lops { get; set; }
    }
}
