//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ESM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phong
    {
        public phong()
        {
            this.lichhocvus = new HashSet<lichhocvu>();
        }
    
        public string MaPhong { get; set; }
        public Nullable<short> KichThuoc { get; set; }
        public string KhoaQL { get; set; }
        public Nullable<short> SucChua { get; set; }
    
        public virtual khoa khoa { get; set; }
        public virtual ICollection<lichhocvu> lichhocvus { get; set; }
    }
}
