//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class giaovien
    {
        public giaovien()
        {
            this.CaThis = new HashSet<CaThi>();
        }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Mã giáo viên")]
        [StringLength(5, MinimumLength = 1, ErrorMessage = "Dài từ 1 tới 5 ký tự")]
        public string MaGiaoVien { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Tên giáo viên")]
        [StringLength(15, ErrorMessage = "Không dài quá 15 kí tự")]
        public string TenGiaoVien { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Bộ môn quản lý")]
        [StringLength(5, MinimumLength = 1, ErrorMessage = "Dài từ 1 tới 5 ký tự")]
        public string BoMonQL { get; set; }

        [DisplayName("Họ lót")]
        [StringLength(25, ErrorMessage = "Không được dài quá 25 ký tự")]
        public string HoLot { get; set; }

        [DisplayName("Học hàm")]
        [StringLength(10, ErrorMessage = "Không được dài quá 10 ký tự")]
        public string HocHam { get; set; }

        [DisplayName("Học vị")]
        [StringLength(10, ErrorMessage = "Không được dài quá 10 ký tự")]
        public string HocVi { get; set; }
    
        public virtual bomon bomon { get; set; }
        public virtual ICollection<CaThi> CaThis { get; set; }
    }
}
