//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class monhoc
    {
        public monhoc()
        {
            this.nhoms = new HashSet<nhom>();
            this.This = new HashSet<Thi>();
        }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Mã môn học")]
        [StringLength(7,MinimumLength = 1, ErrorMessage = "Dài từ 1 tới 7 ký tự")]
        public string MaMonHoc { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Tên môn học")]
        [StringLength(60, ErrorMessage = "Không được dài quá 60 kí tự")]
        public string TenMonHoc { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("TC lý thuyết")]
        [DataType(DataType.Currency, ErrorMessage = "Phải nhập số")] 
        public byte TCLyThuyet { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("TC thực hành")]
        [DataType(DataType.Currency, ErrorMessage = "Phải nhập số")] 
        public byte TCThucHanh { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Môn thí nghiệm")]
        [Range(0, 1, ErrorMessage = "Chỉ được nhập 1 hoặc 0")]
        [DataType(DataType.Currency,ErrorMessage = "Phải nhập số")] 
        public byte MonThiNghiem { get; set; }

        public string KhoaXepLich { get; set; }

        [DisplayName("Bộ môn quản lý")]
        [Required(ErrorMessage = "Không được để trống")]
        public string BoMonQL { get; set; }

        [DisplayName("Ghi chú")]
        [StringLength(500, ErrorMessage = "Không được dài quá 500 ký tự")]
        public string GhiChu { get; set; }

        [DisplayName("Bộ môn")]
        public virtual bomon bomon { get; set; }
        public virtual khoa khoa { get; set; }
        public virtual ICollection<nhom> nhoms { get; set; }
        public virtual ICollection<Thi> This { get; set; }
    }
}
