//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class phong
    {
        public phong()
        {
            this.lichhocvus = new HashSet<lichhocvu>();
            this.This = new HashSet<Thi>();
        }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Mã phòng")]
        [StringLength(10, MinimumLength = 1, ErrorMessage = "Dài từ 1 tới 10 ký tự")]
        public string MaPhong { get; set; }

        [DisplayName("Kích thước")]
        [DataType(DataType.Currency, ErrorMessage = "Phải nhập số")] 
        public Nullable<short> KichThuoc { get; set; }

        [DisplayName("Khoa quản lý")]
        [StringLength(2, ErrorMessage = "Không dài quá 2 kí tự")]
        public string KhoaQL { get; set; }

        [DisplayName("Sức chứa")]
        [DataType(DataType.Currency, ErrorMessage = "Phải nhập số")] 
        public Nullable<short> SucChua { get; set; }
    
        public virtual khoa khoa { get; set; }
        public virtual ICollection<lichhocvu> lichhocvus { get; set; }
        public virtual ICollection<Thi> This { get; set; }
    }
}
