//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UsersRoles = new HashSet<UsersRoles>();
        }
    
        public string ID { get; set; }
        public string Detail { get; set; }
    
        public virtual ICollection<UsersRoles> UsersRoles { get; set; }
    }
}
