//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhvien
    {
        public sinhvien()
        {
            this.pdkmhs = new HashSet<pdkmh>();
            this.This = new HashSet<Thi>();
        }
    
        public string MaSinhVien { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public Nullable<byte> Phai { get; set; }
        public Nullable<System.DateTime> NgaySinh_Ori { get; set; }
        public string NoiSinh { get; set; }
        public string ChuyenNganh { get; set; }
        public string Lop { get; set; }
        public string NgaySinh { get; set; }
    
        public virtual chuyennganh chuyennganh1 { get; set; }
        public virtual lop lop1 { get; set; }
        public virtual ICollection<pdkmh> pdkmhs { get; set; }
        public virtual ICollection<Thi> This { get; set; }
    }
}
