//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class sinhvien
    {
        public sinhvien()
        {
            this.pdkmhs = new HashSet<pdkmh>();
            this.This = new HashSet<Thi>();
        }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Mã số sinh viên")]
        [StringLength(8, MinimumLength = 1, ErrorMessage = "Dài từ 1 tới 8 ký tự")]
        public string MaSinhVien { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Họ")]
        [StringLength(25, ErrorMessage = "Không dài quá 25 kí tự")]
        public string Ho { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Tên")]
        [StringLength(15, ErrorMessage = "Không dài quá 15 kí tự")]
        public string Ten { get; set; }

        [DisplayName("Phái")]
        public Nullable<byte> Phai { get; set; }
        public Nullable<System.DateTime> NgaySinh_Ori { get; set; }

        [DisplayName("Nơi sinh")]
        [StringLength(25, ErrorMessage = "Không dài quá 25 kí tự")]
        public string NoiSinh { get; set; }

        [DisplayName("Chuyên ngành")]
        [StringLength(4, ErrorMessage = "Không dài quá 4 kí tự")]
        public string ChuyenNganh { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [DisplayName("Lớp")]
        [StringLength(10, ErrorMessage = "Không dài quá 10 kí tự")]
        public string Lop { get; set; }

        [DisplayName("Ngày sinh")]
        public string NgaySinh { get; set; }
    
        public virtual chuyennganh chuyennganh1 { get; set; }
        public virtual lop lop1 { get; set; }
        public virtual ICollection<pdkmh> pdkmhs { get; set; }
        public virtual ICollection<Thi> This { get; set; }
    }
}
